ktor:
    development: true
    application:
        modules:
            - indi.gromov.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://postgres/cinema_db"
  user: gromov
  password: gromov_password