services:
  postgres:
    image: postgres:17.4
    container_name: cinema_database
    environment:
      POSTGRES_DB: "cinema_db"
      POSTGRES_USER: "gromov"
      POSTGRES_PASSWORD: "gromov_password"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 1s
      timeout: 10s
  application:
    container_name: app
    ports:
      - "8080:8080"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy